// This file mirrors the structure generated by FlutterFire CLI.
// It is a temporary placeholder so the app can compile before you run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=karigarwoodwork --platforms=android
// The CLI will overwrite this file with real values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // iOS/macOS/web are not configured yet
      default:
        return android;
    }
  }

  // Known identifiers from your request are prefilled to avoid typos.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: '381747502075',
    projectId: 'karigarwoodwork',
    storageBucket: 'karigarwoodwork.appspot.com',
  );
}
